// <auto-generated />
using System;
using AlphaBetaBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AlphaBetaBot.Data.Migrations
{
    [DbContext(typeof(AbfDbContext))]
    partial class AbfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AlphaBetaBot.Data.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2020, 1, 28, 20, 7, 18, 248, DateTimeKind.Unspecified).AddTicks(6035), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<decimal?>("RaidSignupChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("AlphaBetaBot.Data.Raid", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2020, 1, 28, 20, 7, 18, 237, DateTimeKind.Unspecified).AddTicks(6244), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<int>("RaidLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("RaidTime")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaidLocationId");

                    b.ToTable("raids");
                });

            modelBuilder.Entity("AlphaBetaBot.Data.RaidLocation", b =>
                {
                    b.Property<int>("RaidLocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("RaidLocationId");

                    b.ToTable("raid_locations");

                    b.HasData(
                        new
                        {
                            RaidLocationId = 0,
                            Name = "Onyxia"
                        },
                        new
                        {
                            RaidLocationId = 1,
                            Name = "MoltenCore"
                        },
                        new
                        {
                            RaidLocationId = 2,
                            Name = "BlackwingLair"
                        },
                        new
                        {
                            RaidLocationId = 3,
                            Name = "ZulGurub"
                        },
                        new
                        {
                            RaidLocationId = 4,
                            Name = "AQ20"
                        },
                        new
                        {
                            RaidLocationId = 5,
                            Name = "AQ40"
                        },
                        new
                        {
                            RaidLocationId = 6,
                            Name = "Naxxramas"
                        });
                });

            modelBuilder.Entity("AlphaBetaBot.Data.RaidParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RaidId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SignedUpAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RaidId");

                    b.ToTable("raid_participants");
                });

            modelBuilder.Entity("AlphaBetaBot.Data.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2020, 1, 28, 20, 7, 18, 225, DateTimeKind.Unspecified).AddTicks(1950), new TimeSpan(0, 0, 0, 0, 0)));

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AlphaBetaBot.Data.WowCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OwnerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("AlphaBetaBot.Data.Raid", b =>
                {
                    b.HasOne("AlphaBetaBot.Data.RaidLocation", "RaidLocation")
                        .WithMany()
                        .HasForeignKey("RaidLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaBetaBot.Data.RaidParticipant", b =>
                {
                    b.HasOne("AlphaBetaBot.Data.WowCharacter", "Character")
                        .WithMany("RaidsAttending")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaBetaBot.Data.Raid", "Raid")
                        .WithMany("Participants")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaBetaBot.Data.WowCharacter", b =>
                {
                    b.HasOne("AlphaBetaBot.Data.User", "Owner")
                        .WithMany("Characters")
                        .HasForeignKey("OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
